version: '3.3'
services:
  post_db:
    image: mongo:${POST_DB}
    volumes:
      - post_db:/data/db
    networks:
      - reddit_back
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
